# Generated by Django 2.1.2 on 2018-11-07 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_masters', to='main.Salon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Master', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Masters',
            },
        ),
    ]
